package com.netappsid.binding.beans;

import java.beans.PropertyDescriptor;

import org.junit.Assert;
import org.junit.Test;

import com.netappsid.test.beans.TestBean;

public class SimplePropertyAdapterTest
{
	@Test
	public void getPropertyName()
	{
		final SimplePropertyAdapter adapter = new SimplePropertyAdapter(new BeanAdapter(new TestBean("1")), TestBean.PROPERTYNAME_PROPERTY1);

		Assert.assertEquals(TestBean.PROPERTYNAME_PROPERTY1, adapter.getPropertyName());
	}

	@Test
	public void getPropertyDescriptor_NullBeanReturnsNull()
	{
		final SimplePropertyAdapter adapter = new SimplePropertyAdapter(new BeanAdapter(null), TestBean.PROPERTYNAME_PROPERTY1);

		Assert.assertNull(adapter.getPropertyDescriptor());
	}

	@Test
	public void getPropertyDescriptor_NonAdaptablePropertyReturnsNull()
	{
		final SimplePropertyAdapter adapter = new SimplePropertyAdapter(new BeanAdapter(new TestBean("1")), "nonExisting");

		Assert.assertNull(adapter.getPropertyDescriptor());
	}

	@Test
	public void getPropertyDescriptor_AdaptablePropertyReturnsValidPropertyDescriptor()
	{
		final SimplePropertyAdapter adapter = new SimplePropertyAdapter(new BeanAdapter(new TestBean("1")), TestBean.PROPERTYNAME_PROPERTY1);
		final PropertyDescriptor propertyDescriptor = adapter.getPropertyDescriptor();

		Assert.assertNotNull(propertyDescriptor);
		Assert.assertEquals(TestBean.PROPERTYNAME_PROPERTY1, propertyDescriptor.getName());
		Assert.assertEquals(String.class, propertyDescriptor.getPropertyType());
		Assert.assertEquals("getProperty1", propertyDescriptor.getReadMethod().getName());
		Assert.assertEquals("setProperty1", propertyDescriptor.getWriteMethod().getName());
	}

	@Test
	public void getValue_NullBeanReturnsNull()
	{
		final SimplePropertyAdapter adapter = new SimplePropertyAdapter(new BeanAdapter(null), TestBean.PROPERTYNAME_PROPERTY1);

		Assert.assertNull(adapter.getValue());
	}

	@Test
	public void getValue_NonAdaptablePropertyReturnsNull()
	{
		final SimplePropertyAdapter adapter = new SimplePropertyAdapter(new BeanAdapter(new TestBean("1")), "nonExisting");

		Assert.assertNull(adapter.getValue());
	}

	@Test
	public void getValue_AdaptablePropertyReturnsBeanPropertyValue()
	{
		final TestBean bean = new TestBean("1");
		final SimplePropertyAdapter adapter = new SimplePropertyAdapter(new BeanAdapter(bean), TestBean.PROPERTYNAME_PROPERTY1);

		bean.setProperty1("TEST");
		Assert.assertEquals("TEST", adapter.getValue());
	}

	@Test
	public void setValue_NullBeanDoesntGenerateException()
	{
		final SimplePropertyAdapter adapter = new SimplePropertyAdapter(new BeanAdapter(null), TestBean.PROPERTYNAME_PROPERTY1);

		try
		{
			adapter.setValue("TEST");
		}
		catch (Exception e)
		{
			Assert.fail("No exception should be generated by doing this call.");
		}
	}

	@Test
	public void setValue_NonAdaptablePropertyDoesntGenerateException()
	{
		final SimplePropertyAdapter adapter = new SimplePropertyAdapter(new BeanAdapter(new TestBean("1")), "nonExisting");

		try
		{
			adapter.setValue("TEST");
		}
		catch (Exception e)
		{
			Assert.fail("No exception should be generated by doing this call.");
		}
	}
	
	@Test
	public void setValue_AdaptablePropertySetsBeanValue()
	{
		final TestBean bean = new TestBean("1");
		final SimplePropertyAdapter adapter = new SimplePropertyAdapter(new BeanAdapter(bean), TestBean.PROPERTYNAME_PROPERTY1);

		adapter.setValue("TEST");
		Assert.assertEquals("TEST", bean.getProperty1());
	}
}
